#
# Module manifest for module 'New-ShortCut'
#
# Generated by: RocketToast
#
# Generated on: 8/8/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\New-ShortCut.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = @(5.1)

# ID used to uniquely identify this module
GUID = '75ce7a30-f565-446d-bf40-2678129b18ca'

# Author of this module
Author = 'RocketToast'

# Copyright statement for this module
Copyright = '(c) RocketToast. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Create a new .url or .lnk shortcut in Windows'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("Windows", "Shortcut", "URL")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/RocketToast/New-Shortcut/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/RocketToast/New-Shortcut'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

}

